### ISSUE TITLE
Select XML by opening and saving existing workspaces by default

### ISSUE THREAD

**Issue by NathanKatwijk** [HUSACCT/HUSACCT#228]
By importing a new workspace, you could only select the format XML by now. Because this is the only possibility, I think it would be better to select XML by default as well:

https://www.dropbox.com/s/55z0d2ldz7hti4h/Importeren%20workspace.png

https://www.dropbox.com/s/5b9c99wphlgyzi8/Importeren%20workspace%202.png

This happens in the screen 'Save Workspace' as well.

Participant: @bwstaal

**Comment by LeoHU** [comment]
Solved
