### ISSUE TITLE
Interface Figure behaviour

### ISSUE THREAD

**Issue by MonkeySleeve** [HUSACCT/HUSACCT#252]
As you can see in the screenshots, the bounds of an interface figure are incorrect. When you try and move the interface it enlarges itself to these bounds and will keep increasing in size. I spend a few hours trying to fix the problem but I couldn't find where it was coming from. It may have something to do the setBounds() method within InterfaceFigure begin called 2 times when the diagram is drawn.

![interfacebug](https://f.cloud.github.com/assets/3717190/676146/d5a79d46-d8ff-11e2-994f-af1df76a9fb4.png)
![interfacebug2](https://f.cloud.github.com/assets/3717190/676145/d59ba18a-d8ff-11e2-9e2a-18b25b8613b4.png)

**Comment by LeoHU** [comment]
Solved
