### ISSUE TITLE
Workspace crash on opening/creating/saving workspace on half-screen

### ISSUE THREAD

**Issue by CodingContraption** [HUSACCT/HUSACCT#273]
While having the husacct tool snapped on the right half of my screen on my 1920x1080 screen I noticed the application kept freezing when I tried to create, open or save a workspace.

Running full screen, regular windowed or snapped to the left side of the screen it's working just fine.

I am running on windows 8.1 64-bit, Running Java version 7 update 71.

**Comment by LeoHU** [comment]
Problem solved.
