### ISSUE TITLE
HUSACCT doesn't close when hitting the Save & Exit button on exit confirm screen.

### ISSUE THREAD

**Issue by tomvlk** [HUSACCT/HUSACCT#274]
When trying to quit the application it remains active when hitting Save & Exit on the confirm screen.
(Windows 10)

Actions to reproduce:
1. Start HUSACCT with project
2. Open Implementation Architecture Diagram
3. Hit ALT+F4 or the Windows Close button
4. Hit Save & Exit
5. Click on save
6. Here it should close the application but it doesn't!

**Comment by LeoHU** [comment]
Issue is solved and the solution will be included in the next release.
