### ISSUE TITLE
Bug bij verwijderen van component

### ISSUE THREAD

**Issue by wouterfennis** [HUSACCT/HUSACCT#280]
Als je op een project de Scanniello layer identification los laat.
Vervolgens doe je op een layer de Component and Subsystem identification
Dan haal je een gevonden map/compontent weg
Vervolgens doe je weer de Component and Subsystem identification
Je krijgt dan een leeg error bericht (3x) en de UI van HUSACCT zie je veranderen maar wat er precies gebeurt weet je niet.

**Comment by wouterfennis** [comment]
Daarna is trouwens de applicatie onbruikbaar

**Comment by LeoHU** [comment]
Solved in 5.0.1
