### ISSUE TITLE
Modules and Dependencies diagram resizing 

### ISSUE THREAD

**Issue by p4k03n4t0r** [HUSACCT/HUSACCT#281]
Als er een Modules and Dependencies diagram is gemaakt met meerdere layers moeten er meerdere layers geselecteerd worden en erop ingezoomt worden. Vervolgens kunnen de layers verplaatst en resizet worden. Bij het resizen van een layer vanaf links-onder, links, links-boven, boven en rechts-boven wordt de layer verplaatst i.p.v. geresizet.

**Comment by gertkommer** [comment]
De figuren vereisen een minimale grootte. Standaard staat het figuur al op de minimale grote. als je het figuur kleiner maakt dan mogelijk is dan verplaatst het figuur. Als het figuur groter is dan de minimale grootte dan kan het figuur wel kleiner worden gemaakt.
