### ISSUE TITLE
External Library Rule Issue

### ISSUE THREAD

**Issue by Bouke454** [HUSACCT/HUSACCT#286]
Leeg scherm bij het selecteren van een External library en het toevoegen van een regel ervan

Bij het volgen van de SAP 4 opdracht wordt er in stap 1.2 gevraagd om regels toe te voegen. Maar de daar beschreven handelingen leiden tot bijgevoegd scherm, ALS per ongeluk een external system nog is geselecteerd.  

Ik verwacht hier een foutmelding
http://prnt.sc/dh9kce

**Comment by LeoHU** [comment]
Solved 2017-03-31.
