### ISSUE TITLE
Classes are not being shown in the intended architecture [HUSACCT_5.4.jar]

### ISSUE THREAD

**Issue by fons-000** [HUSACCT/HUSACCT#308]
When you go to the implemented architecture on version 5.4 of HUSACCT (analysing HUSACCTS own code for this example) with the source code for the workspace at ...\src\husacct\ you can see the following image, if you press Analyse implemented architecture => Implemented architecture diagram and click on the hussact package.

![image](https://user-images.githubusercontent.com/55665983/133516168-891ffe76-139d-40ad-ad29-46dc6a123909.png)

As you can see, I can see both classes and packages, which is totally fine. If I open another package, it'll show me the correct packages, classes and interfaces 1 level lower.

The problem lies however, in the intended architecture.

------------

When I click Analyse implemented architecture => Reconstruct architecture and then choose the approach _Iterative identification of layers, components, and subsystems - Within selected module (or root) - With external systems_. I get a quick intended architecture for HUSACCT.

The problem with this intended architecture is that: I can't see classes in my subsystems (packages). A good example will be the following picture.

![implementedArchitectureDiagramHUSACCTCommit](https://user-images.githubusercontent.com/55665983/133517629-0142b0b3-83ac-40f3-b8a1-f89aa5d06e07.PNG)

Now, we can see that the code package _husacct.graphics.presentation.tables_ is assigned to this tables subsystem. You would think that you could see the classes in this package, in the intended architecture, right? Our implemented architecture concludes that it consist of the classes: _DependencyDataModel, DependencyTable, RuleDataModel, RuleTable, UmlLinkDataModel, UmlLinkDataModel, UmlLinkTable, ViolationDataModel and ViolationTable_ shown in the picture below.

![softwareUnits](https://user-images.githubusercontent.com/55665983/133518093-61a56cce-963c-477f-8e92-14a4ade07d87.PNG)

Now, when I'm in the intended architecture diagram menu and I've clicked to graphics.presentation, I will see the following diagram of this package.

![graphicsPresentationPicture](https://user-images.githubusercontent.com/55665983/133518505-7b6573c0-82e5-4a0a-a2c6-3da0ad1e3444.PNG)

Now, when I double click on tables, nothing happens. Even when I replace the software unit tables packages, with all it;s classes instead (option 1) OR include it all in assigned software units (option 2); still nothing happens when I double click on tables.

Option 1

![option1](https://user-images.githubusercontent.com/55665983/133519190-b01d0ddc-2d12-46f5-abbb-a08cc63da63a.PNG)

Option 2

![option2](https://user-images.githubusercontent.com/55665983/133519073-6120b5ba-04f9-4ce6-9361-ab15f120298e.PNG)

------------

I hope I described the problem as clearly as possible. To summarize it:

1. I can't see classes that are assigned to software modules in the three structure of the intended architecture.
2. I can't click on a subsystem and see the dependency relations between the code classes in it.

**Comment by LeoHU** [comment]
Hi fons-000,
This is not a problem or bug, but a misunderstanding from your side. The intended architecture diagram shows only modules in the intended architecture. Since there are no submodules of 'tables' in your intended architecture, nothing can be shown. Assigned software units and their relationships can be shown with options in the implemented architecture menu. Or create modules for them in the intended architecture and then they will be shown in the intended architecture diagram.

Note: This is not the place to learn the functionality of the tool.
